// Static mock data — used when DATABASE_URL is not configured
import type { Category, Product, BlogPost } from "@prisma/client";

export const mockCategories: Category[] = [
  { id: "1", name: "Engine Parts", slug: "engine-parts", description: "High-performance engine components", image: null, icon: "⚙️", sortOrder: 1, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: "2", name: "Suspension", slug: "suspension", description: "Precision suspension systems", image: null, icon: "🔧", sortOrder: 2, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: "3", name: "Brakes", slug: "brakes", description: "Premium braking systems", image: null, icon: "🛑", sortOrder: 3, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: "4", name: "Body Parts", slug: "body-parts", description: "Exterior body components", image: null, icon: "🚗", sortOrder: 4, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: "5", name: "Electrical", slug: "electrical", description: "Electrical systems and components", image: null, icon: "⚡", sortOrder: 5, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: "6", name: "Transmission", slug: "transmission", description: "Gearbox and drivetrain parts", image: null, icon: "🔩", sortOrder: 6, isActive: true, createdAt: new Date(), updatedAt: new Date() },
];

export const mockProducts: (Product & { category: Category })[] = [
  {
    id: "1", name: "Porsche 911 Turbo Engine Mount", slug: "porsche-911-turbo-engine-mount",
    description: "OEM engine mount for Porsche 911 Turbo. Precision engineered for optimal performance and vibration dampening.",
    shortDesc: "OEM engine mount — perfect fitment guaranteed", sku: "POR-911T-EM-001",
    status: "AVAILABLE", tag: "OEM", images: [],
    categoryId: "1", category: mockCategories[0],
    brands: ["Porsche"], models: ["911 Turbo", "911 Turbo S"], years: [2019, 2020, 2021, 2022, 2023],
    variants: ["Turbo", "Turbo S"], fuelTypes: ["Petrol"], countrySpecs: ["GCC", "Euro"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: true, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: "2", name: "BMW M5 Carbon Ceramic Brake Kit", slug: "bmw-m5-carbon-ceramic-brake-kit",
    description: "Performance carbon ceramic brake kit for BMW M5. Exceptional stopping power with reduced weight.",
    shortDesc: "Carbon ceramic — track-grade stopping power", sku: "BMW-M5-CCB-001",
    status: "AVAILABLE", tag: "PERFORMANCE", images: [],
    categoryId: "3", category: mockCategories[2],
    brands: ["BMW"], models: ["M5", "M5 Competition"], years: [2018, 2019, 2020, 2021, 2022, 2023],
    variants: ["M5", "M5 Competition"], fuelTypes: ["Petrol"], countrySpecs: ["GCC", "Euro", "US"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: true, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: "3", name: "Mercedes-Benz G63 AMG Suspension Kit", slug: "mercedes-g63-suspension-kit",
    description: "Complete suspension overhaul kit for Mercedes-Benz G63 AMG. Improved handling and ride comfort.",
    shortDesc: "Full suspension kit for G63 AMG", sku: "MB-G63-SUSP-001",
    status: "ON_REQUEST", tag: "OEM", images: [],
    categoryId: "2", category: mockCategories[1],
    brands: ["Mercedes-Benz"], models: ["G63 AMG", "G-Class"], years: [2019, 2020, 2021, 2022, 2023],
    variants: ["AMG"], fuelTypes: ["Petrol"], countrySpecs: ["GCC", "Euro"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: true, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: "4", name: "Land Rover Defender Body Panel Set", slug: "land-rover-defender-body-panel",
    description: "Complete body panel replacement set for Land Rover Defender. OEM quality fitment.",
    shortDesc: "OEM body panels for Defender", sku: "LR-DEF-BP-001",
    status: "AVAILABLE", tag: "OEM", images: [],
    categoryId: "4", category: mockCategories[3],
    brands: ["Land Rover"], models: ["Defender"], years: [2020, 2021, 2022, 2023],
    variants: ["90", "110", "130"], fuelTypes: ["Petrol", "Diesel"], countrySpecs: ["GCC", "Euro", "UK"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: true, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: "5", name: "Toyota Land Cruiser 300 ECU Module", slug: "toyota-lc300-ecu-module",
    description: "Genuine Toyota ECU module for Land Cruiser 300 series. Plug and play replacement.",
    shortDesc: "Genuine ECU for LC300", sku: "TOY-LC300-ECU-001",
    status: "AVAILABLE", tag: "OEM", images: [],
    categoryId: "5", category: mockCategories[4],
    brands: ["Toyota"], models: ["Land Cruiser 300"], years: [2021, 2022, 2023],
    variants: ["GXR", "VXR", "Sahara"], fuelTypes: ["Petrol"], countrySpecs: ["GCC"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: true, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: "6", name: "Nissan Patrol Y62 Gearbox Rebuild Kit", slug: "nissan-patrol-y62-gearbox-kit",
    description: "Complete gearbox rebuild kit for Nissan Patrol Y62. All seals, bearings and gaskets included.",
    shortDesc: "Full gearbox rebuild kit for Y62", sku: "NIS-Y62-GBX-001",
    status: "ON_REQUEST", tag: "AFTERMARKET", images: [],
    categoryId: "6", category: mockCategories[5],
    brands: ["Nissan"], models: ["Patrol"], years: [2016, 2017, 2018, 2019, 2020, 2021, 2022],
    variants: ["Y62", "Platinum"], fuelTypes: ["Petrol"], countrySpecs: ["GCC"],
    metaTitle: null, metaDesc: null, viewCount: 0, inquiryCount: 0,
    isFeatured: false, isActive: true, createdAt: new Date(), updatedAt: new Date(),
  },
];

export const mockBlogPosts: (BlogPost & { author: { name: string; avatar: string | null } })[] = [
  {
    id: "1", title: "Top 5 OEM Parts Every Luxury Car Owner Should Know About",
    slug: "top-5-oem-parts-luxury-cars",
    excerpt: "Understanding the difference between OEM, aftermarket, and performance parts can save you thousands.",
    content: "<p>When it comes to maintaining your luxury vehicle, choosing the right parts is critical...</p>",
    coverImage: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
    tags: ["OEM", "Luxury Cars", "Maintenance"], category: "Maintenance Tips",
    metaTitle: null, metaDesc: null, isPublished: true,
    publishedAt: new Date("2024-01-15"), viewCount: 245, authorId: "1",
    author: { name: "RR Auto Revamp", avatar: null },
    createdAt: new Date("2024-01-15"), updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2", title: "GCC vs Euro Spec: What's the Difference?",
    slug: "gcc-vs-euro-spec-difference",
    excerpt: "A complete guide to understanding country specifications and why they matter for your vehicle.",
    content: "<p>Country specifications affect everything from cooling systems to suspension tuning...</p>",
    coverImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    tags: ["GCC Spec", "Euro Spec", "Guide"], category: "Buying Guide",
    metaTitle: null, metaDesc: null, isPublished: true,
    publishedAt: new Date("2024-02-10"), viewCount: 189, authorId: "1",
    author: { name: "RR Auto Revamp", avatar: null },
    createdAt: new Date("2024-02-10"), updatedAt: new Date("2024-02-10"),
  },
  {
    id: "3", title: "How to Identify Genuine vs Counterfeit Auto Parts",
    slug: "genuine-vs-counterfeit-auto-parts",
    excerpt: "Protect your vehicle and wallet by learning how to spot fake parts before they cause damage.",
    content: "<p>The counterfeit auto parts market costs the industry billions annually...</p>",
    coverImage: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80",
    tags: ["Genuine Parts", "Safety", "Tips"], category: "Tips & Tricks",
    metaTitle: null, metaDesc: null, isPublished: true,
    publishedAt: new Date("2024-03-05"), viewCount: 312, authorId: "1",
    author: { name: "RR Auto Revamp", avatar: null },
    createdAt: new Date("2024-03-05"), updatedAt: new Date("2024-03-05"),
  },
];
