import type { Lead, LeadNote } from "@prisma/client";

export const mockLeads: (Lead & { product: { name: string; slug: string } | null })[] = [
  {
    id: "lead-1", type: "PRODUCT_INQUIRY", status: "NEW", score: "HOT",
    name: "Rahul Sharma", email: "rahul@example.com", phone: "+91 98765 43210",
    company: "Sharma Motors", country: "India",
    brand: "BMW", model: "M5", year: 2022, variant: "Competition",
    fuelType: "Petrol", countrySpec: "Euro", chassisNumber: "WBS83CH0XPC123456",
    partName: "Carbon Ceramic Brake Kit", partNumber: "BMW-M5-CCB-001",
    quantity: 1, message: "Need urgent replacement for my M5 Competition",
    attachments: [], productId: "2", product: { name: "BMW M5 Carbon Ceramic Brake Kit", slug: "bmw-m5-carbon-ceramic-brake-kit" },
    source: "website", utmSource: null, utmMedium: null, utmCampaign: null,
    ipAddress: "192.168.1.1", userAgent: null,
    contactedAt: null, closedAt: null,
    createdAt: new Date("2024-03-01T10:30:00"), updatedAt: new Date("2024-03-01T10:30:00"),
  },
  {
    id: "lead-2", type: "GENERAL_INQUIRY", status: "CONTACTED", score: "WARM",
    name: "Priya Patel", email: "priya@example.com", phone: "+91 87654 32109",
    company: null, country: "India",
    brand: "Porsche", model: "911 Turbo", year: 2021, variant: "Turbo S",
    fuelType: "Petrol", countrySpec: "GCC", chassisNumber: null,
    partName: "Engine Mount", partNumber: "POR-911T-EM-001",
    quantity: 2, message: "Looking for OEM engine mounts for my 911",
    attachments: [], productId: "1", product: { name: "Porsche 911 Turbo Engine Mount", slug: "porsche-911-turbo-engine-mount" },
    source: "website", utmSource: null, utmMedium: null, utmCampaign: null,
    ipAddress: null, userAgent: null,
    contactedAt: new Date("2024-03-02T14:00:00"), closedAt: null,
    createdAt: new Date("2024-03-02T09:15:00"), updatedAt: new Date("2024-03-02T14:00:00"),
  },
  {
    id: "lead-3", type: "BULK_INQUIRY", status: "QUALIFIED", score: "HOT",
    name: "Amit Singh", email: "amit@garagepro.in", phone: "+91 76543 21098",
    company: "GaragePro Delhi", country: "India",
    brand: "Mercedes-Benz", model: "G63 AMG", year: 2023, variant: "AMG",
    fuelType: "Petrol", countrySpec: "GCC", chassisNumber: null,
    partName: "Suspension Kit", partNumber: "MB-G63-SUSP-001",
    quantity: 5, message: "We need 5 sets for our fleet customers",
    attachments: [], productId: "3", product: { name: "Mercedes-Benz G63 AMG Suspension Kit", slug: "mercedes-g63-suspension-kit" },
    source: "website", utmSource: null, utmMedium: null, utmCampaign: null,
    ipAddress: null, userAgent: null,
    contactedAt: new Date("2024-03-03T11:00:00"), closedAt: null,
    createdAt: new Date("2024-03-03T08:00:00"), updatedAt: new Date("2024-03-03T11:00:00"),
  },
  {
    id: "lead-4", type: "PRODUCT_INQUIRY", status: "NEW", score: "COLD",
    name: "Vikram Mehta", email: "vikram@example.com", phone: "+91 65432 10987",
    company: null, country: "India",
    brand: "Toyota", model: "Land Cruiser 300", year: 2022, variant: "VXR",
    fuelType: "Petrol", countrySpec: "GCC", chassisNumber: null,
    partName: "ECU Module", partNumber: null,
    quantity: 1, message: null,
    attachments: [], productId: "5", product: { name: "Toyota Land Cruiser 300 ECU Module", slug: "toyota-lc300-ecu-module" },
    source: "website", utmSource: null, utmMedium: null, utmCampaign: null,
    ipAddress: null, userAgent: null,
    contactedAt: null, closedAt: null,
    createdAt: new Date("2024-03-04T16:45:00"), updatedAt: new Date("2024-03-04T16:45:00"),
  },
  {
    id: "lead-5", type: "GENERAL_INQUIRY", status: "CLOSED", score: "WARM",
    name: "Neha Gupta", email: "neha@example.com", phone: "+91 54321 09876",
    company: "Luxury Auto Delhi", country: "India",
    brand: "Land Rover", model: "Defender", year: 2021, variant: "110",
    fuelType: "Diesel", countrySpec: "Euro", chassisNumber: null,
    partName: "Body Panel Set", partNumber: "LR-DEF-BP-001",
    quantity: 1, message: "Need front bumper and hood replacement",
    attachments: [], productId: "4", product: { name: "Land Rover Defender Body Panel Set", slug: "land-rover-defender-body-panel" },
    source: "website", utmSource: null, utmMedium: null, utmCampaign: null,
    ipAddress: null, userAgent: null,
    contactedAt: new Date("2024-03-01T10:00:00"), closedAt: new Date("2024-03-05T12:00:00"),
    createdAt: new Date("2024-02-28T14:20:00"), updatedAt: new Date("2024-03-05T12:00:00"),
  },
];

export const mockLeadNotes: Record<string, (LeadNote & { author: { name: string } })[]> = {
  "lead-2": [
    {
      id: "note-1", content: "Called customer, they confirmed they need 2 units. Will send quote by EOD.",
      leadId: "lead-2", authorId: "mock-admin-001",
      author: { name: "Super Admin" },
      createdAt: new Date("2024-03-02T14:00:00"),
    },
  ],
  "lead-3": [
    {
      id: "note-2", content: "Bulk order confirmed. Checking stock availability with supplier.",
      leadId: "lead-3", authorId: "mock-admin-001",
      author: { name: "Super Admin" },
      createdAt: new Date("2024-03-03T11:00:00"),
    },
  ],
};
